INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Regional','(11) 91111-1111','ABC Ferramentas Ltda');
INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Regional','(11) 2222-2222','Mega Construcoes Ltda');
INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Nacional','(19) 93333-3333','QualiFerramentas');
INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Nacional','(19) 4444-4444','Mega Construcoes e Ferramentas');
INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Internacional','+55 (11) 95555-5555','Construcenter');
INSERT INTO TBL_FORNEC (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Internacional','+55 (19) 6666-6666','Porcas&Parafusos');
